import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/swiper.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { StoreProvider } from "./storeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <StoreProvider>
          <Header />
          <main className="bg-white min-h-screen p-4  pt-20">{children}</main>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
